/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testeweka;

import java.io.File;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import weka.classifiers.bayes.NaiveBayes;
import weka.core.DenseInstance;
import weka.core.Instance;
import weka.core.Instances;
import weka.core.converters.ConverterUtils.DataSource;
/**
 *
 * @author carlos
 */
public class CadastrarAluno extends javax.swing.JFrame {
    ArrayList<Aluno> alunos = new ArrayList();
    DefaultTableModel modeloTabela =  new DefaultTableModel();
    DataSource ds;
    Instances ins;
    NaiveBayes nb = new NaiveBayes();

    /**
     * Creates new form CadastrarAluno
     */
    public CadastrarAluno() {
        initComponents();
        modeloTabela = (DefaultTableModel)Tabela.getModel();
        //modeloTabela.removeRow(0);
        //modeloTabela.removeRow(1);
        for(int i = 0; i <=  modeloTabela.getRowCount(); i++){
            modeloTabela.removeRow(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboPeriodo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        comboSexo = new javax.swing.JComboBox<>();
        radioItaperuna = new javax.swing.JRadioButton();
        radioTrabalha = new javax.swing.JRadioButton();
        radioCasado = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        comboOrigem = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        comboIngresso = new javax.swing.JComboBox<>();
        radioCota = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        comboLocomocao = new javax.swing.JComboBox<>();
        comboTempoChegada = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        comboDependencias = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        comboPerdeuPeriodo = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        comboAfinidade = new javax.swing.JComboBox<>();
        btRegistrar = new javax.swing.JButton();
        comboIdade = new javax.swing.JComboBox<>();
        comboFilhos = new javax.swing.JComboBox<>();
        btCarregarArquivo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        btAferirMotivacao = new javax.swing.JButton();
        btAlterarTela = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Período");

        jLabel2.setText("Idade");

        comboPeriodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1° Período", "2° Período", "3° Período", "4° Período", "5° Período", "6° Período", "7° Período", "8° Período" }));

        jLabel3.setText("Sexo");

        comboSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino" }));

        radioItaperuna.setText("Mora em Itaperuna?");

        radioTrabalha.setText("Trabalha?");

        radioCasado.setText("Casado?");

        jLabel4.setText("Filhos");

        jLabel5.setText("Origem");

        comboOrigem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Particular", "Estadual", "Federal" }));

        jLabel6.setText("Ingresso");

        comboIngresso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ENEM", "Vestibular", "Transferencia" }));

        radioCota.setText("Cota?");

        jLabel7.setText("Locomoção");

        comboLocomocao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carro", "Moto", "Outros", "Onibus" }));

        comboTempoChegada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "30m", "1h-2h", "30min-1h", "Sup2h" }));

        jLabel8.setText("Tempo para Chegada");

        jLabel9.setText("Dependencias");

        comboDependencias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1a2", "3a5", "Maisde5" }));

        jLabel10.setText("Perdeu de Período");

        comboPerdeuPeriodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1a2", "3a5", "Maisde5" }));

        jLabel11.setText("Afinidade");

        comboAfinidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administracao", "AnalProjetoSistemas", "DesenvdeSistemas", "InfraRedes", "Matematica" }));

        btRegistrar.setText("Registrar");
        btRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistrarActionPerformed(evt);
            }
        });

        comboIdade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "17-20", "21-29", "29-30", "MaisDe30" }));

        comboFilhos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "zero", "um", "dois", "tres", "MaiDe3" }));

        btCarregarArquivo.setText("Carregar Arquvo");
        btCarregarArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCarregarArquivoActionPerformed(evt);
            }
        });

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Periodo", "Idade", "Locomoção", "Motivação"
            }
        ));
        jScrollPane1.setViewportView(Tabela);

        btAferirMotivacao.setText("Aferir Motivação");
        btAferirMotivacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAferirMotivacaoActionPerformed(evt);
            }
        });

        btAlterarTela.setText("Filtrar Regras");
        btAlterarTela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarTelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(comboTempoChegada, javax.swing.GroupLayout.Alignment.LEADING, 0, 200, Short.MAX_VALUE)
                                    .addComponent(comboSexo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboPeriodo, 0, 200, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                                .addComponent(jLabel8))
                            .addComponent(comboIdade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(comboDependencias, javax.swing.GroupLayout.Alignment.LEADING, 0, 123, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(comboLocomocao, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(comboPerdeuPeriodo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(comboIngresso, 0, 176, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(comboFilhos, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(radioItaperuna, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(radioCasado, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(radioCota)
                                    .addComponent(radioTrabalha)
                                    .addComponent(comboOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboAfinidade, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btCarregarArquivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btAferirMotivacao)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btAlterarTela)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(btAlterarTela)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioItaperuna)
                    .addComponent(radioTrabalha)
                    .addComponent(comboPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioCasado)
                    .addComponent(radioCota))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboFilhos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboLocomocao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboIngresso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboTempoChegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboDependencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboPerdeuPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(btRegistrar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboAfinidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btCarregarArquivo))
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btAferirMotivacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(28, 28, 28)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistrarActionPerformed
       Aluno aluno = new Aluno();
       switch ( comboPeriodo.getSelectedIndex()) {
         case 0 :
         {
           aluno.setPeriodo("1oP");  
           break;
         }
         case 1 :
         {
           aluno.setPeriodo("2oP");
           break;
         }
         case 2 :
         {
           aluno.setPeriodo("3oP");
           break;
         }
         case 3 :
         {
           aluno.setPeriodo("4oP");
           break;
         }
         case 4 :
         {
           aluno.setPeriodo("5oP");
           break;
         }
         case 5 :
         {
           aluno.setPeriodo("6oP");
           break;
         }
         case 6 :
         {
           aluno.setPeriodo("7oP");
           break;
         }
         case 7 :
         {
           aluno.setPeriodo("8oP");
           break;
         }
       }
       
       aluno.setIdade(comboIdade.getSelectedItem().toString());
       aluno.setFilhos(comboFilhos.getSelectedItem().toString());
       aluno.setSexo(comboSexo.getSelectedItem().toString());
       aluno.setOrigem(comboOrigem.getSelectedItem().toString());
       aluno.setIngresso(comboIngresso.getSelectedItem().toString());
       aluno.setLocomocao(comboLocomocao.getSelectedItem().toString());
       aluno.setTempoChegar(comboTempoChegada.getSelectedItem().toString());
       aluno.setDependecias(comboDependencias.getSelectedItem().toString());
       aluno.setPerdeu(comboPerdeuPeriodo.getSelectedItem().toString());
       aluno.setAfinidade(comboAfinidade.getSelectedItem().toString());
       
       if (radioItaperuna.isSelected()){
           aluno.setMoraemitap("Sim");
       } else {
           aluno.setMoraemitap("Nao");
       }
       
       if (radioCasado.isSelected()){
           aluno.setCasado("Sim");
       } else {
           aluno.setCasado("Nao");
       }
       
       if (radioCota.isSelected()){
           aluno.setCota("Sim");
       } else {
           aluno.setCota("Nao");
       }
       
       if (radioTrabalha.isSelected()){
           aluno.setTrabalha("Sim");
       } else {
           aluno.setTrabalha("Nao");
       }
       
       alunos.add(aluno);
    }//GEN-LAST:event_btRegistrarActionPerformed

    private void carregarArquivo(String caminho) throws Exception{
        System.out.println(caminho);
        this.ds = new DataSource(caminho);
        this.ins = ds.getDataSet();
        
        ins.setClassIndex(15);
        nb.buildClassifier(ins);
    }
    
    private void btCarregarArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCarregarArquivoActionPerformed
        File arquivos  = null;
        JFileChooser fc = new JFileChooser();
        fc.setDialogTitle("Escolha o(s) arquivo(s)...");
        fc.setDialogType(JFileChooser.OPEN_DIALOG);
        fc.setApproveButtonText("OK");
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fc.setMultiSelectionEnabled(true);
        int resultado = fc.showOpenDialog(fc);
        
        try {
             if (resultado == JFileChooser.APPROVE_OPTION){
               arquivos = fc.getSelectedFile();
                 try {
                     this.carregarArquivo(arquivos.getPath());
                 } catch (Exception ex) {
                     Logger.getLogger(InterfacePrograma.class.getName()).log(Level.SEVERE, null, ex);
                 }
             }
            //System.out.println(arquivos.getPath());
            //this.carregarArquivo(arquivos.getPath());
            
            // listaAtributo = new JList(lista);  
        } catch (Exception ex) {
            Logger.getLogger(InterfacePrograma.class.getName()).log(Level.SEVERE, null, ex);
        }                                       
    }//GEN-LAST:event_btCarregarArquivoActionPerformed

    private void btAferirMotivacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAferirMotivacaoActionPerformed
        // TODO add your handling code here:
       // ins.setClassIndex(15);
       // try {
       //     nb.buildClassifier(ins);
       // } catch (Exception ex) {
       //     Logger.getLogger(CadastrarAluno.class.getName()).log(Level.SEVERE, null, ex);
       // }
        Instance novo = new DenseInstance(16);
        novo.setDataset(ins);
       // novo.setValue(0, "1oP");
       //     novo.setValue(1, "17-20");
       //     novo.setValue(2, "Masculino");
       //     novo.setValue(3, "Sim");
       //     novo.setValue(4, "Sim");
       //     novo.setValue(5, "Sim");
       //     novo.setValue(6, "zero");
           // novo.setValue(7, "Estadual");
           // novo.setValue(8, "ENEM");      
           // novo.setValue(9, "Sim");      
           // novo.setValue(10, "Carro");      
           // novo.setValue(11, "30m");      
           // novo.setValue(12, "0");      
           // novo.setValue(13, "0");      
           // novo.setValue(14, "Administracao"); 
        for (Aluno a : alunos) {
            System.out.println(a.toString());  
            novo.setValue(0, a.getPeriodo());
            novo.setValue(1, a.getIdade());
            novo.setValue(2, a.getSexo());
            novo.setValue(3, a.getMoraemitap());
            novo.setValue(4, a.getTrabalha());
            novo.setValue(5, a.getCasado());
            novo.setValue(6, a.getFilhos());
            novo.setValue(7, a.getOrigem());
            novo.setValue(8, a.getIngresso());      
            novo.setValue(9, a.getCota());      
            novo.setValue(10, a.getLocomocao());      
            novo.setValue(11, a.getTempoChegar());      
            novo.setValue(12, a.getDependecias());      
            novo.setValue(13, a.getPerdeu());      
            novo.setValue(14, a.getAfinidade()); 
            
            
            
            try {
               double probabilidade[] = nb.distributionForInstance(novo);
               double somar = 0;
               
               int index_maiormotivacao = 0;
               for(int i = 0; i<probabilidade.length; i++){
                 System.out.println("Motivacao index" + i + ": " + probabilidade[i]);
                 if(probabilidade[i] > probabilidade[index_maiormotivacao])
                   index_maiormotivacao = i;
               }
               a.setMotivacao(""+ (index_maiormotivacao));
            } catch (Exception ex) {
                Logger.getLogger(CadastrarAluno.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            modeloTabela.addRow(new Object[]{a.getPeriodo(), a.getIdade(), a.getLocomocao(), a.getMotivacao()});
        }
        
        alunos.clear();
        
        
    }//GEN-LAST:event_btAferirMotivacaoActionPerformed

    private void btAlterarTelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarTelaActionPerformed
        // TODO add your handling code here:
        InterfacePrograma form = new InterfacePrograma();
        form.show();
        
    }//GEN-LAST:event_btAlterarTelaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabela;
    private javax.swing.JButton btAferirMotivacao;
    private javax.swing.JButton btAlterarTela;
    private javax.swing.JButton btCarregarArquivo;
    private javax.swing.JButton btRegistrar;
    private javax.swing.JComboBox<String> comboAfinidade;
    private javax.swing.JComboBox<String> comboDependencias;
    private javax.swing.JComboBox<String> comboFilhos;
    private javax.swing.JComboBox<String> comboIdade;
    private javax.swing.JComboBox<String> comboIngresso;
    private javax.swing.JComboBox<String> comboLocomocao;
    private javax.swing.JComboBox<String> comboOrigem;
    private javax.swing.JComboBox<String> comboPerdeuPeriodo;
    private javax.swing.JComboBox<String> comboPeriodo;
    private javax.swing.JComboBox<String> comboSexo;
    private javax.swing.JComboBox<String> comboTempoChegada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioCasado;
    private javax.swing.JRadioButton radioCota;
    private javax.swing.JRadioButton radioItaperuna;
    private javax.swing.JRadioButton radioTrabalha;
    // End of variables declaration//GEN-END:variables
}
