/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testeweka;

import java.io.File;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JList;
import weka.associations.Apriori;
import weka.core.Instances;
import weka.core.converters.ConverterUtils.DataSource;
import weka.filters.Filter;
import weka.filters.unsupervised.attribute.Remove;

/**
 *
 * @author carlos
 */
public class InterfacePrograma extends javax.swing.JFrame {
    private DefaultListModel lista            = new DefaultListModel();
    private DefaultListModel listaSelecionado = new DefaultListModel();
    /**
     * Creates new form InterfacePrograma
     */
    DataSource ds;
    Instances data;
    public InterfacePrograma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaAtributo = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaAtributoSelecionado = new javax.swing.JList<>();
        removerAtributo2 = new javax.swing.JButton();
        adicionarAtributo2 = new javax.swing.JButton();
        btGerar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        listaAtributo.setName("listaAtrinuto"); // NOI18N
        jScrollPane1.setViewportView(listaAtributo);

        jButton1.setText("Importar Arquivo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(listaAtributoSelecionado);

        removerAtributo2.setText("<<");
        removerAtributo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerAtributo2ActionPerformed(evt);
            }
        });

        adicionarAtributo2.setText(">>");
        adicionarAtributo2.setName("adicionarAtributo"); // NOI18N
        adicionarAtributo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarAtributo2ActionPerformed(evt);
            }
        });

        btGerar.setText("Gerar");
        btGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(adicionarAtributo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(removerAtributo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(53, 53, 53)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(41, 41, 41)
                .addComponent(btGerar)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 70, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(adicionarAtributo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(removerAtributo2)
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(btGerar))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowActivated
    private void carregarArquivo(String caminho) throws Exception{
        System.out.println(caminho);
        //caminho = "src/testeweka/respostas.arff";
        ds = new DataSource(caminho);
        data = ds.getDataSet();
        
        data.setClassIndex(data.numAttributes() - 1);

        Apriori apriori = new Apriori();
        apriori.setClassIndex(data.classIndex());
        apriori.buildAssociations(data);
        
        ArrayList<Atributo> atributos = new ArrayList();

        for (int i = 0; i < data.numAttributes(); i++) {
            Atributo a = new Atributo();
            a.setNome(data.attribute(i).name());
            ArrayList<String> valores = new ArrayList();
            for (int j = 0; j < data.attribute(i).numValues(); j++) {
                valores.add(data.attribute(i).value(j));
            }
            a.setValores(valores);
            atributos.add(a);
        }
        
        for (Atributo a : atributos) {
            lista.addElement(a.getNome());
            //System.out.println(a.getNome() + ": " + a.getValores());
        }
        listaAtributo.setModel(lista);
        //System.out.println(listaAtributo.getModel().getElementAt(1).toString());
    }
            
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
 //       lista.addElement("teste");
 //       listaAtributo.setModel(lista);
        File arquivos  = null;
        JFileChooser fc = new JFileChooser();
        fc.setDialogTitle("Escolha o(s) arquivo(s)...");
        fc.setDialogType(JFileChooser.OPEN_DIALOG);
        fc.setApproveButtonText("OK");
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fc.setMultiSelectionEnabled(true);
        int resultado = fc.showOpenDialog(fc);
        
        try {
             if (resultado == JFileChooser.APPROVE_OPTION){
               arquivos = fc.getSelectedFile();
                 try {
                     this.carregarArquivo(arquivos.getPath());
                 } catch (Exception ex) {
                     Logger.getLogger(InterfacePrograma.class.getName()).log(Level.SEVERE, null, ex);
                 }
             }
            //this.carregarArquivo("");
            
            // listaAtributo = new JList(lista);  
        } catch (Exception ex) {
            Logger.getLogger(InterfacePrograma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void adicionarAtributo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarAtributo2ActionPerformed
        // TODO add your handling code here:
        listaSelecionado.addElement(listaAtributo.getModel().getElementAt(listaAtributo.getSelectedIndex()).toString());
        listaAtributoSelecionado.setModel(listaSelecionado);
        lista.remove(listaAtributo.getSelectedIndex());
        //listaAtributo.remove(listaAtributo.getSelectedIndex());
    }//GEN-LAST:event_adicionarAtributo2ActionPerformed

    
    private void removerAtributo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerAtributo2ActionPerformed
        // TODO add your handling code here:
        lista.addElement(listaAtributoSelecionado.getModel().getElementAt(listaAtributoSelecionado.getSelectedIndex()).toString());
        listaAtributo.setModel(lista);
        listaSelecionado.remove(listaAtributoSelecionado.getSelectedIndex());
    }//GEN-LAST:event_removerAtributo2ActionPerformed

    private void btGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerarActionPerformed
        // TODO add your handling code here:
        DataSource ds;
        int[] indices = new int[listaSelecionado.getSize()];
        String [] valor = new String[2];
        try {
           // ds = new DataSource("");
            
          //  Instances data = ds.getDataSet();
          //  data.setClassIndex(data.numAttributes() - 1);

          //  Apriori apriori = new Apriori();
          //  apriori.setClassIndex(data.classIndex());
          //  apriori.buildAssociations(data);
            
            Remove remove = new Remove();
            Instances newData = data;
            
         //   System.out.println(listaSelecionado.getElementAt(1).toString());
         
            ArrayList<String> valores = new ArrayList();
            valor[0] = "-R";
            for (int i = 0; i < listaSelecionado.size(); i++){
              indices[i] = data.attribute(listaSelecionado.getElementAt(i).toString()).index();
              valor[1]   = valor[1] +  "" + data.attribute(listaSelecionado.getElementAt(i).toString()).index();
              
              if (i != listaSelecionado.size() -1){
                valor[1] = valor[1] + ","  ;
              }   
            }
            
           remove.setAttributeIndicesArray(indices);
           remove.setInvertSelection(true);
           remove.setOptions(valor);
           remove.setInputFormat(data);
           newData = Filter.useFilter(data, remove);
           
           //System.out.println(newData);
           //System.out.println(valor[0]);
            //System.out.println(remove.getAttributeIndices());
            
            //Filter filter = new Filter() {};
           // filter.setOptions(options);
            
        //    newData = Filter.useFilter(newData, remove);
            
           // for (int i = 0; i < listaSelecionado.size(); i++){
           //   System.out.println("" + newData.attribute(i).toString());
           // }
        } catch (Exception ex) {
            Logger.getLogger(InterfacePrograma.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //System.out.println(data.toString());

        
    }//GEN-LAST:event_btGerarActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfacePrograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfacePrograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfacePrograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfacePrograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
          
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfacePrograma().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarAtributo2;
    private javax.swing.JButton btGerar;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listaAtributo;
    private javax.swing.JList<String> listaAtributoSelecionado;
    private javax.swing.JButton removerAtributo2;
    // End of variables declaration//GEN-END:variables
}
